version: "3.7"

services:
  db:
    image: mysql
    container_name: ${DB_NAME}
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:3333
    volumes:
     - .:/home/app/property_rental
     - /home/app/property_rental/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
